# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_documentdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentdata',
            options={'verbose_name': '文档资料', 'verbose_name_plural': '文档资料'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '视频教程', 'verbose_name_plural': '视频教程'},
        ),
    ]
