# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 02:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170902_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='course_introduction',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程大纲'),
        ),
        migrations.AddField(
            model_name='news',
            name='student_comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='学员评价'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程介绍'),
        ),
    ]
