# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 10:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20170905_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='videourl',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='百度云盘URL'),
        ),
    ]
