# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20171112_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycar',
            options={'ordering': ['date_added'], 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AddField(
            model_name='buycar',
            name='cart_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='buycar',
            table='cart_items',
        ),
    ]
