# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_remove_admin_buy_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='buy_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.BuyCar'),
        ),
    ]
