# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_remove_admin_buy_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='product',
        ),
        migrations.AddField(
            model_name='buycar',
            name='product',
            field=models.ManyToManyField(to='app01.News'),
        ),
    ]
