# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20171112_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='product',
        ),
        migrations.AddField(
            model_name='buycar',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.News'),
        ),
    ]
