# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20171112_0321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buycar',
            table='BuyCar',
        ),
    ]
