# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_auto_20171112_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='product',
        ),
        migrations.DeleteModel(
            name='BuyCar',
        ),
    ]
