# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_auto_20171112_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.News')),
            ],
            options={
                'ordering': ['date_added'],
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'BuyCar',
            },
        ),
    ]
