# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_auto_20171112_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycar',
            old_name='cart_id',
            new_name='cart_owner',
        ),
    ]
