# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_auto_20171112_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='总价格'),
        ),
    ]
