# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_admin_my_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_uuid', models.CharField(max_length=100, unique=True, verbose_name='购物清单uuid')),
                ('total_num', models.IntegerField(blank=True, default=0, verbose_name='已选商品数')),
                ('total_price', models.IntegerField(blank=True, default=0, verbose_name='已选商品合计')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('buyers', models.CharField(max_length=100, unique=True, verbose_name='购买者')),
                ('total_goods', models.ManyToManyField(blank=True, null=True, to='app01.News')),
            ],
        ),
    ]
