# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_auto_20171119_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='list_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='app uuid', verbose_name='app uuid'),
        ),
    ]
