# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_goodslist_ifpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='课程标题')),
                ('courses_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.News')),
            ],
            options={
                'verbose_name': '我要开课',
                'verbose_name_plural': '我要开课',
            },
        ),
    ]
