# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_news_check_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courses_video',
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_video',
            field=models.ManyToManyField(blank=True, null=True, to='app01.News'),
        ),
    ]
