# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_auto_20171128_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='course_introduction',
        ),
        migrations.RemoveField(
            model_name='news',
            name='student_comments',
        ),
        migrations.AddField(
            model_name='courses',
            name='check_enable',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
        migrations.AddField(
            model_name='courses',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程介绍'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_introduction',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程大纲'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='课程价格(默认免费)'),
        ),
        migrations.AddField(
            model_name='courses',
            name='favor_count',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='courses',
            name='focus_count',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='courses',
            name='newpic',
            field=models.ImageField(default='statics/upload_imgss/logo.jpg', upload_to='statics/images/', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='courses',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='courses',
            name='student_comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='学员评价'),
        ),
    ]
