# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_auto_20171128_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程内容'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='课程内容'),
        ),
    ]
