# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0042_courses_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courses_video',
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
