# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0045_gotvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gotvideo',
            options={'verbose_name': '我购买的视频', 'verbose_name_plural': '我购买的视频'},
        ),
        migrations.AddField(
            model_name='gotvideo',
            name='buyers',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='购买者'),
        ),
    ]
